### ISSUE TITLE
Ruby Group Capstone Project

### ISSUE THREAD

**Issue by usmansbk** [usmansbk/ruby-group-project#5]
Project: [Kanban Board](https://github.com/usmansbk/ruby-group-project/projects/1)

This project is composed of the following 3 members:

- `Team member #1`: Usman @usmansbk 
- `Team member #2`: Denis @denisdiaconu
- `Team member #3`: Gift @Ghiftee

**Comment by Davidosky007** [comment]
## Hi @usmansbk @Ghiftee @denisdiaconu 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
## Congratulations! 🎉 
![good-job-gif](https://user-images.githubusercontent.com/52497246/137688461-1911d24d-5f47-4a5f-9d40-a95525b0cd3b.gif)



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
